# Generated by Django 4.2.1 on 2025-01-10 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
